# Generated by Django 4.1.3 on 2023-04-10 10:02

import Blog.modules
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('comment', models.TextField()),
                ('date', models.CharField(default=Blog.modules.commentDate, max_length=35)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='Blog.blog')),
            ],
        ),
    ]
